### PR TITLE
Do not query same attribute more than once

### LINKED ISSUE #564: Queries are broken if translates is called multiple times
The query scopes (Klass.i18n) stop working correctly if translates is called twice in a model class:
```ruby
class Model < ActiveRecord::Base
  translates :name 
  translates :name 
end
```
(not that it makes sense to do that, but it can happen due to class reloading etc)
The scope then generates queries like: `WHERE "table_translations_en"."name" = 'Name' AND "table_translations_en"."name" IS NULL`, so it never returns any records.

The issue is that `translates` does an `include Mobility.translations_class.new` every time, so it will add two `#<Translations (Mobility::Backends::ActiveRecord::Table) @names=name>` into Klass.ancestors. Then the query patches enumerate the modules with `scope.model.ancestors.grep(::Mobility::Translations)` and this will return 2 instances instead of 1, which results in adding bogus conditions to the query.

### PR DESCRIPTION
**Pull request by shioyama**
Fixes #564

### CODE REVIEW

**Comment by shioyama** [comment]
@mrbrdo This should fix #564, have a look. If it looks good I'll make a 1.2.7 patch and release that right away.

File: spec/mobility/plugins/active_record/query_spec.rb [hunk 1]
```diff
@@ -192,4 +192,29 @@
...
+
+      expect(Article.i18n.where(title: "Title")).to eq([article])
+    end
+
+    it "handles intersecting attribute declarations" do
+      stub_const 'Article', Class.new(ActiveRecord::Base)
+      translates Article, :title, :content, backend: :key_value, type: :string
+
+      # title defined below clobbers title defined above
+      translates Article, :title, backend: :table
```
Comment (shioyama) [inline spec/mobility/plugins/active_record/query_spec.rb:211]: Maybe we should issue a warning, but for now this at least handles the situation gracefully.
