### PR TITLE
Fix duping for AR KeyValue backend

### LINKED ISSUE #123: Dup does not dup translations (KeyValue backend)
#84 fixed this issue for the Table backend, but it is still broken for the KeyValue backend.

## Context

`dup` does not duplicate translations. Suppose we have:

```ruby
post = Post.new
post.title = "foo"
post.save
post.title
#=> "foo"
post_dup = post.dup
```

## Expected Behavior

The `title` of the dup'ed post should be `"foo"`:

```ruby
post_dup.title
#=> "foo"
```

## Actual Behavior

The `title` is nil, because the translations are not dup'ed:

```ruby
post_dup.title
#=> nil
```

There is already a spec for this which is [disabled](https://github.com/shioyama/mobility/blob/38d458f3ebc9eb18c3d29b4b5fa4a71ba1bcf4e2/spec/support/shared_examples/dup_examples.rb#L54-L58) for KeyValue backends (AR + Sequel), so if someone works on this, just remove that skip code and make the test pass.

### PR DESCRIPTION
**Pull request by shioyama**
Fixes #123

### CODE REVIEW

File: lib/mobility/backends/active_record/key_value.rb [hunk 1]
```diff
@@ -70,6 +70,19 @@ def self.configure(options)
...
         after_destroy :mobility_destroy_key_value_translations
 
+        module_name = "MobilityArKeyValue#{association_name.to_s.camelcase}"
+        unless const_defined?(module_name)
+          callback_methods = Module.new do
+            define_method :initialize_dup do |source|
+              super(source)
+              self.send("#{association_name}=", source.send(association_name).map(&:dup))
+              # Set inverse on associations
+              send(association_name).each { |translation| translation.translatable = self }
```
Comment (shioyama) [inline lib/mobility/backends/active_record/key_value.rb]: If I leave out the spec checking that changing the attribute on one instance does not affect the value on the other instance, then this can be simplified to just:

```ruby
define_method :initialize_dup do |source|
  super(source)
  self.send("#{association_name}=", source.send(association_name))
end
```

i.e. you don't need to dup the association objects, nor set the inverse.

However, I personally think that it's better that the dup'ed instance does not affect the original and vice versa. However, Sequel (for example) does not "deep dup" for any pattern here used in the backends... I suppose because there's a performance cost, and Sequel always defaults to not incurring any performance hits.

Comment (shioyama) [reply lib/mobility/backends/active_record/key_value.rb]: Never mind, we definitely want duplicate models to have their own translations with AR at least. I think this is the correct way to fix this.
